# -*- coding: utf-8 -*-
"""Arabic Intelligent NLP System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zAN9WsbNXykmhskv0jK7Ap_f7b_4wPW
"""

from google.colab import drive
drive.mount('/content/drive')

import os

project_path = "/content/drive/MyDrive/arabic_bert_project"

os.makedirs(project_path, exist_ok=True)

print("Project folder created!")

folders = ["data", "models", "notebooks"]

for folder in folders:
    os.makedirs(os.path.join(project_path, folder), exist_ok=True)

print("All folders ready!")

!pip install transformers
!pip install datasets
!pip install torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "aubmindlab/bert-base-arabertv2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=5
)

text = "هذا المشروع رائع جدا"

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

outputs = model(**inputs)

print(outputs)

from datasets import load_dataset

dataset = load_dataset("labr")

dataset

dataset["train"][0]

def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

print(dataset["train"].column_names)

tokenized_datasets.set_format("torch")

# ================================
# 1. تثبيت المكتبات
# ================================
!pip install transformers datasets torch -q

# ================================
# 2. ربط Google Drive
# ================================
from google.colab import drive
drive.mount('/content/drive')

# ================================
# 3. تحميل المكتبات
# ================================
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
import torch

# ================================
# 4. تحميل الموديل (مع عدد الفئات)
# ================================
model_name = "aubmindlab/bert-base-arabertv2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=5
)

# ================================
# 5. تحميل البيانات
# ================================
dataset = load_dataset("labr")

# ================================
# 6. Tokenization
# ================================
def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# ================================
# 7. تجهيز البيانات
# ================================
tokenized_datasets = tokenized_datasets.remove_columns(["text"])
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
tokenized_datasets.set_format("torch")

# ================================
# 8. زيادة حجم البيانات (تحسين الدقة)
# ================================
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(2000))
small_test_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(400))

# ================================
# 9. إعداد التدريب (محسّن)
# ================================
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/arabic_bert_project/models",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=2,   # 👈 مهم للتحسين
    weight_decay=0.01,
    logging_dir="/content/logs",
)

# ================================
# 10. Trainer
# ================================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_test_dataset,
)

# ================================
# 11. التدريب
# ================================
trainer.train()

# ================================
# 12. التقييم
# ================================
trainer.evaluate()

# ================================
# 13. حفظ الموديل
# ================================
trainer.save_model("/content/drive/MyDrive/arabic_bert_project/models/my_model")

# ================================
# 14. تجربة النموذج
# ================================
model.eval()

text = "هذا المنتج ممتاز جدا وأنصح به"

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits
predicted_class_id = torch.argmax(logits, dim=1).item()

labels_map = {
    0: "سيء جدا",
    1: "سيء",
    2: "محايد",
    3: "جيد",
    4: "ممتاز"
}

print("النص:", text)
print("التصنيف:", labels_map[predicted_class_id])

print("✅ تم التدريب والتجربة بنجاح!")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model.to(device)

text = "هذا المنتج ممتاز جدا وأنصح به"

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

# 👇 ننقل البيانات إلى نفس الجهاز
inputs = {key: value.to(device) for key, value in inputs.items()}

model.eval()

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits
predicted_class_id = torch.argmax(logits, dim=1).item()

labels_map = {
    0: "سيء جدا",
    1: "سيء",
    2: "محايد",
    3: "جيد",
    4: "ممتاز"
}

print("النص:", text)
print("التصنيف:", labels_map[predicted_class_id])

from transformers import pipeline

ner = pipeline(
    "ner",
    model="CAMeL-Lab/bert-base-arabic-camelbert-msa-ner",
    tokenizer="CAMeL-Lab/bert-base-arabic-camelbert-msa-ner"
)

text = "زار محمد بن سلمان مدينة الرياض أمس"

results = ner(text)

for entity in results:
    print(f"الكلمة: {entity['word']} | النوع: {entity['entity']}")

!pip install pyarabic -q

!pip install sumy -q

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer

text = """
الذكاء الاصطناعي أصبح من أهم التقنيات الحديثة التي تستخدم في العديد من المجالات مثل الطب والتعليم والصناعة.
يساعد الذكاء الاصطناعي في تحسين الكفاءة وتوفير الوقت والجهد، كما يساهم في اتخاذ قرارات دقيقة بناءً على البيانات.
كما أن استخدام الذكاء الاصطناعي يزداد بشكل كبير في السنوات الأخيرة.
"""

parser = PlaintextParser.from_string(text, Tokenizer("arabic"))
summarizer = LsaSummarizer()

summary = summarizer(parser.document, 2)  # عدد الجمل في الملخص

print("الملخص:")
for sentence in summary:
    print(sentence)

!pip install --upgrade transformers

def improved_qa(context, question):
    sentences = context.split(".")

    question_words = question.split()
    best_sentence = ""
    max_score = 0

    for sentence in sentences:
        score = sum(1 for word in question_words if word in sentence)

        if score > max_score:
            max_score = score
            best_sentence = sentence

    return best_sentence.strip()


context = """
الذكاء الاصطناعي يستخدم في مجالات متعددة مثل الطب والتعليم والصناعة.
يساعد في تحسين الكفاءة واتخاذ القرارات.
"""

question = "في أي مجالات يستخدم الذكاء الاصطناعي؟"

answer = improved_qa(context, question)

print("السؤال:", question)
print("الإجابة:", answer)

!pip install streamlit pyngrok -q

import ipywidgets as widgets
from IPython.display import display
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# =========================
# تحميل الموديل (مرة واحدة فقط)
# =========================
model_path = "/content/drive/MyDrive/arabic_bert_project/models/my_model"

tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv2")
model = AutoModelForSequenceClassification.from_pretrained(model_path)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

labels_map = {
    0: "سيء جدا",
    1: "سيء",
    2: "محايد",
    3: "جيد",
    4: "ممتاز"
}

# =========================
# QA function
# =========================
def improved_qa(context, question):
    sentences = context.split(".")
    question_words = question.split()

    best_sentence = ""
    max_score = 0

    for sentence in sentences:
        score = sum(1 for word in question_words if word in sentence)
        if score > max_score:
            max_score = score
            best_sentence = sentence

    return best_sentence.strip()

# =========================
# واجهة المستخدم
# =========================
text_input = widgets.Textarea(
    value='',
    placeholder='اكتب النص هنا...',
    description='النص:',
    layout=widgets.Layout(width='100%', height='100px')
)

task_dropdown = widgets.Dropdown(
    options=['تحليل المشاعر', 'تلخيص النص', 'سؤال وجواب'],
    description='المهمة:'
)

question_input = widgets.Text(
    value='',
    placeholder='اكتب السؤال هنا...',
    description='السؤال:'
)

button = widgets.Button(description="تشغيل 🚀")
output = widgets.Output()

# =========================
# عند الضغط
# =========================
def on_button_click(b):
    with output:
        output.clear_output()
        text = text_input.value

        if not text.strip():
            print("⚠️ أدخل نص أولاً")
            return

        task = task_dropdown.value

        if task == "تحليل المشاعر":
            inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
            inputs = {k: v.to(device) for k, v in inputs.items()}

            with torch.no_grad():
                outputs = model(**inputs)

            pred = torch.argmax(outputs.logits, dim=1).item()
            print("💡 النتيجة:", labels_map[pred])

        elif task == "تلخيص النص":
            sentences = text.split(".")
            summary = ".".join(sentences[:2])
            print("✂️ الملخص:")
            print(summary)

        elif task == "سؤال وجواب":
            question = question_input.value
            if not question.strip():
                print("⚠️ أدخل السؤال")
                return

            answer = improved_qa(text, question)
            print("💬 الإجابة:")
            print(answer)

button.on_click(on_button_click)

# =========================
# عرض الواجهة
# =========================
display(text_input, task_dropdown, question_input, button, output)

!streamlit run app.py &>/dev/null &

import time
time.sleep(5)

from google.colab.output import eval_js

print(eval_js("google.colab.kernel.proxyPort(8501)"))

import os

base = "/content/drive/MyDrive/arabic_nlp_project"

folders = ["data", "models", "notebooks", "app"]

for f in folders:
    os.makedirs(os.path.join(base, f), exist_ok=True)

print("تم إنشاء الهيكل")

import shutil

src = "/content/drive/MyDrive/arabic_bert_project/models/my_model"
dst = "/content/drive/MyDrive/arabic_nlp_project/models/my_model"

shutil.copytree(src, dst, dirs_exist_ok=True)

print("تم نقل الموديل")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/drive/MyDrive/arabic_nlp_project/app/app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/drive/MyDrive/arabic_nlp_project/app/app.py
# 
# print("واجهة المشروع")